include:
  - ../../api-gateway/compose.yaml
  - ../../Identity/docker-compose.yml
  - ../../discordia-chat/docker-compose.yml
  - ../../community/docker-compose.yml

networks:
  red-local:
    driver: bridge